### ISSUE TITLE
Flatpak package not seen system pip packages

### ISSUE THREAD

**Issue by balzamon** [flathub/com.jetbrains.PyCharm-Community#38]
I installed Pycharm.flatpak package but flatpak version does not use system pip packages from /usr/lib/python3.7/site-package. It is a big problem because I need them. I try to install them locally but no way some of them not installable via pip.

**Comment by TingPing** [comment]
Yes it is sandboxed, it cannot use the host `/usr`. You can use other paths such as the home one though.

**Comment by balzamon** [comment]
I understand that. But PyCharm use python from /usr/bin so this is not a really sandbox mode. It makes no sense to use flatpak version instead of any other version.

**Comment by barthalion** [comment]
`/usr/bin/python` you see in the sandbox is completely different one that you have in the host.

**Comment by balzamon** [comment]
How? I understand the reason but it is bad for me.

**Comment by aleb** [comment]
It runs in a sandbox with its own filesystem which has `/usr/bin/python`. Since none is specified in [com.jetbrains.PyCharm-Community.json](https://github.com/flathub/com.jetbrains.PyCharm-Community/blob/master/com.jetbrains.PyCharm-Community.json) it must be the one from the runtime: `"runtime": "org.freedesktop.Sdk"`.

**Comment by balzamon** [comment]
OK. Thank you!

**Comment by Tasm-Devil** [comment]
Now, everything makes sense. I was wondering, why I see files, that do not exist on my machine. Why is it not possible to change this? Is there any god reason to do it this "sandboxed" way?
